import { fal } from "@fal-ai/client";
import { FAL_IMAGE_CAP_MS, FAL_TRAIN_CAP_MS, FAL_VISION_CAP_MS, falDeadline } from "./fal-deadline";
import { tasks } from "@trigger.dev/sdk";
import type { generateStillsTask } from "@/trigger/stills";
import type { trainPetLoraTask } from "@/trigger/train-lora";
import { OrderStatus, type Order } from "@/generated/prisma/client";
import { prisma } from "./db";
import { transitionOrder } from "./orders";
import { resolveWorld, SHOT_FRAMINGS } from "./film-script";
import { VISION_MODEL, VISION_LLM, publicUrl, scoreIdentity } from "./identity";
import { watermarkTakeForPreview } from "./watermark";
import { sendAdminStoryboardReviewAlert } from "./mocks";
// STORYBOARD-ADMIN-GATE-SPEC.md §3.3(b): pulled in purely to derive
// adminRerollSeedBase's disjointness proof below from the SAME cap the
// customer reroll route enforces, rather than re-hardcoding it.
import { STORYBOARD_REROLL_CAP } from "./safety-net";

/**
 * Storyboard generation — the whole Gate-1 payload, generated BEFORE approval.
 *
 * Likeness is THE conversion moment ("that's my pet!"), and the fix for
 * "cuts 2-6 don't look like my dog" is to put a HUMAN pick on every cut, not
 * just the first. So we front-load the entire storyboard here and let the
 * customer pick one take per cut in the Gate-1 wizard:
 *
 *   Stage 0  describePet      VLM extracts distinguishing features as text
 *                             (coat, mouth/tongue, tail, ears, and — per
 *                             IDENTITY-FIDELITY-SPEC.md §2.3 — how this
 *                             individual deviates from a breed-standard
 *                             example) — injected into every downstream
 *                             prompt so the model can't drift to a generic
 *                             breed prototype.
 *   Stage 1  identityPortrait Neutral studio close-up — locks the face BEFORE
 *                             any costume/scene transformation. Per
 *                             IDENTITY-FIDELITY-SPEC.md §2.4, this is now
 *                             ITSELF gated against the customer's real photo
 *                             (generateGatedPortrait) before anything
 *                             downstream is built from it — this is the
 *                             single highest-leverage gate in the pipeline,
 *                             since a drifted portrait poisons the hero sheet
 *                             AND all 18 takes. The gate's threshold is a
 *                             catastrophe floor, not a quality bar — see
 *                             IDENTITY_THRESHOLD below (LORA-STORYBOARD-SPEC.md
 *                             §4.5).
 *   Stage 2  heroSheet        The pet in the film's LOCKED costume — the
 *                             shared costume anchor for all 18 takes (keeps
 *                             costume identical). NOT the identity anchor —
 *                             see Stage 3.
 *   Stage 3  storyboard       6 cuts × 3 takes = 18 stills. Every take is
 *                             generated by this order's trained LoRA (B1)
 *                             whenever one is available — the hero sheet is
 *                             passed ONLY as a costume reference, never as the
 *                             identity anchor (LORA-STORYBOARD-SPEC.md §2.2).
 *                             No LoRA (fallback): referenced to the customer's
 *                             REAL photo first (identity anchor) + hero sheet
 *                             (costume anchor) + portrait, the pre-B1
 *                             nano-banana chain. Either way, gated against the
 *                             REAL PHOTO for identity AND checked for anatomy
 *                             (LORA-STORYBOARD-SPEC.md §4.2) before the
 *                             customer ever sees it, and rendered with a
 *                             DISTINCT seed so the three takes are genuinely
 *                             different ("similar-to-my-pet" is a real axis to
 *                             choose on).
 *
 * LoRA TRAINING IS NOT A STAGE OF THIS FUNCTION (LORA-STORYBOARD-SPEC.md
 * §2.7). It measured at ~45 minutes (n=1, fal queue time included) — far
 * longer than the "a few minutes" this file originally assumed — so it runs
 * in its OWN upstream Trigger.dev task (trigger/train-lora.ts's
 * "train-pet-lora", built on runLoraTraining/trainPetLora below) that
 * persists `loraUrl`/`loraTriggerWord` on the order and THEN triggers this
 * task. `runStillsGeneration` below only ever READS those two fields off the
 * order it's given — it must never call trainPetLora itself, or a transient
 * failure anywhere in Stage 0-3 (a bad VLM response, a fal hiccup) would
 * retry the whole task and burn another 45 minutes re-training a LoRA that
 * training already produced. See train-pet-lora's own doc comment for the
 * failure-isolation argument in full, and reshootCutStill/rerollCutTakes
 * below for how a re-roll/re-shoot reads the same persisted fields.
 *
 * The film pipeline (lib/film-pipeline.ts) no longer generates stills — it just
 * animates the six the customer picked.
 *
 * Cost: ~$2 (LoRA training, separate task) + $0.01 (VLM) + $0.15 (portrait) +
 * $0.15 (hero) + 18×$0.15 (takes) ≈ $5.0/order. Ops pattern unchanged:
 * detached async in dev, compensating revert to UPLOADING on failure,
 * VIDEO_PIPELINE_MOCK short-circuit for e2e.
 */

// Exported: film-pipeline.ts reuses this exact model id for §5.2's end-frame
// generation (same nano-banana edit call, different caller) rather than
// hardcoding a second copy of the endpoint id.
export const EDIT_MODEL = "fal-ai/nano-banana-pro/edit";

// Exported: app/api/orders/reroll-cut/route.ts validates cutIndex against
// this same bound (0..NUM_CUTS-1) rather than hardcoding "6" a second time.
export const NUM_CUTS = 6;
// Exported for the same reason as NUM_CUTS above (test enumeration).
export const TAKES_PER_CUT = 3;

export const IDENTITY_RULES =
  "Preserve this exact pet's identity from the reference photos: the same coat colors in the same places, the same fur texture and haircut, the same face structure, eyes, ears and proportions. Do NOT idealize, do NOT groom them differently, do NOT drift toward a generic breed look. No text, no watermark, no humans.";

// Style lock — deepspace especially drifts toward a Pixar/CG look, which owners
// read as "not a real photo of my dog". Injected into every take and hero sheet.
export const STYLE_RULES =
  "Strictly photorealistic live-action photography: real fur texture, natural skin of the nose, true-to-life lighting and lens optics. NOT cartoon, NOT CGI, NOT 3D render, NOT illustration, NOT stylized animation.";

// Per-cut framing lives in film-script (SHOT_FRAMINGS) so each cut has its own
// composition (wide/close/low-angle/…) instead of one identical medium shot.

// Identity gate: takes below this score against the customer's REAL PHOTO
// (IDENTITY-FIDELITY-SPEC.md §2.1 — see generateGatedTake) are re-rolled
// before they ever reach the customer.
//
// LORA-STORYBOARD-SPEC.md §4.5: was 80. The owner's own eyeball-sorted bake-off
// (15 takes across CURRENT/A-EDIT/B1/B2a/B2b) showed the "looks like my dog"
// group averaging 78.9 and the "doesn't look like my dog" group averaging
// 78.3 — the SAME score on both sides of a distinction a human makes
// instantly. A threshold of 80 sitting inside that overlap was throwing away
// good takes and re-rolling on pure noise, at real $ and wall-clock cost. Now
// a catastrophe floor, not a quality bar: it exists to catch a wrong species/
// a completely different animal, nothing finer than that. Do NOT raise this
// back up expecting it to separate "good likeness" from "bad likeness" —
// today's data says it structurally cannot; §4.5 is quite explicit that this
// score has no discriminating power in that range. film-pipeline.ts's
// CLIP_IDENTITY_THRESHOLD and END_FRAME_IDENTITY_THRESHOLD get the same
// treatment, per §4.5's explicit instruction to handle them identically.
const IDENTITY_THRESHOLD = 50;
// Exported: scripts/test-safety-net.ts uses this (plus STILL_SEED/NUM_CUTS/
// TAKES_PER_CUT below) to enumerate every seed the ORIGINAL stage-3
// generation can possibly use, so it can prove rerollSeedBase's seeds never
// land in that set — see rerollSeedBase's comment.
export const MAX_TAKE_REROLLS = 2;
/*
 * OFF until the pre-production refund exists.
 *
 * Watermarking Gate 1 has exactly one justification (PRICING-PRODUCT-V2-SPEC
 * §3.5(C)): stopping someone from paying $249, keeping the storyboard,
 * claiming the refund back and walking off with 18 usable 2K stills for the
 * non-refundable fee.
 * That refund is B2 and is not built, so right now the customer cannot get
 * their money back and there is nothing to walk away with — the exploit the
 * marks defend against has no entry point.
 *
 * What the marks do cost is real: soft, marked-up artwork at the exact moment
 * the customer first sees their pet as the star, a paragraph of reassurance
 * that only exists to explain the marks, and a production order lost to an OOM
 * in the render pass. Chargebacks don't argue for it either — the finished
 * film ships clean, so the marks protect nothing there.
 *
 * Set this back to `true` in the same change that ships the refund. Nothing
 * else needs touching: with it off, `preview === clean`, which is already the
 * shape a legacy row and a failed watermark render both produce, so every
 * downstream read (normalizeStoryboard, the props-stripping in Gate1View, the
 * pick resolution in approve-storyboard) behaves exactly as it does today.
 */
const WATERMARK_PREVIEWS_ENABLED = false;
// How many Gate-1 preview derivatives to render at once (see stage 4 below).
// Each one decodes a 2K PNG in ffmpeg, so this is a memory ceiling, not a
// rate limit — 4 keeps the peak flat no matter how many takes exist.
const WATERMARK_CONCURRENCY = 4;
// Base seed; each (cut, take, reroll) gets a distinct offset so the three
// takes of a cut are genuinely different renders, not near-duplicates.
// Exported: rerollSeedBase (below) and scripts/test-safety-net.ts both need
// it to reason about the ORIGINAL stage-3 seed range a B2 re-roll must avoid.
export const STILL_SEED = 77021;

/*
 * B2-SAFETY-NET-SPEC.md §3.1 / "THE PARTS THAT WILL BITE": a re-roll that
 * returns the same three images is a re-roll the customer paid for and
 * didn't get, so its seeds must never collide with a seed already used for
 * THAT SAME CUT (a collision against a DIFFERENT cut doesn't matter — that
 * cut's scene text differs, so an identical numeric seed still renders a
 * different image; see generateTakeOnce's prompt, which always includes the
 * scene).
 *
 * Stage 3 (runStillsGeneration) already uses this exact shape for a cut's 3
 * takes: STILL_SEED + cut*100 + take*1000, then generateGatedTake adds its
 * own attempt*7919 on top for up to MAX_TAKE_REROLLS retries. For one cut,
 * across all TAKES_PER_CUT takes and MAX_TAKE_REROLLS+1 attempts, that's
 * `take*1000 + attempt*7919` for take/attempt in 0..2 — 9 values, all
 * distinct (7919 is prime and not a multiple of 1000, so the map is
 * injective), spanning at most 2000 + 2*7919 = 17838 above the cut's base.
 *
 * REROLL_SEED_BAND is chosen far larger than that whole spread (17838), so a
 * re-roll's seed = STILL_SEED + cut*100 + REROLL_SEED_BAND*rerollCount +
 * take*1000 + attempt*7919 lands in its own band, disjoint from band 0 (the
 * original stage-3 generation) BY CONSTRUCTION — not "very unlikely to
 * collide" the way a Date.now()-derived seed (as reshootCutStill below uses
 * for its own, unrelated, admin-only Gate-2 re-render) would be.
 *
 * `rerollCount` is the ORDER-WIDE, atomically-incremented storyboardRerollCount
 * AFTER increment (1, 2, or 3 — see app/api/orders/reroll-cut/route.ts). The
 * guarded `updateMany` there makes each value 1..STORYBOARD_REROLL_CAP occur
 * for AT MOST ONE reroll request across the order's entire lifetime, so even
 * if the SAME cut is re-rolled twice, those two events land in two different
 * bands (e.g. 1 and 2) and can never repeat each other's seeds either —
 * whether or not they touch the same cut.
 */
const REROLL_SEED_BAND = 1_000_000;

/** See the block comment above — exported so scripts/test-safety-net.ts can
 *  prove the no-collision property directly, without a database. */
export function rerollSeedBase(cutIndex: number, rerollCount: number): number {
  return STILL_SEED + cutIndex * 100 + REROLL_SEED_BAND * rerollCount;
}

/*
 * STORYBOARD-ADMIN-GATE-SPEC.md §3.3(b): the admin's own cut re-roll — used
 * while a storyboard sits in the pre-approval review queue, BEFORE the
 * customer ever sees it (see completeStillsGeneration below) — must never be
 * able to draw a seed a CUSTOMER re-roll could also draw for that same cut.
 * Reusing storyboardRerollCount for this would risk exactly that: an admin
 * re-roll and a later customer re-roll could land on the same (cutIndex,
 * count) pair and rerollSeedBase would hand them the identical seed. That is
 * why adminRerollCount is its OWN column (prisma/schema.prisma) — never
 * storyboardRerollCount, which §3.3(a) also protects for a completely
 * different reason (it is the customer's B2 free-reroll budget, and an
 * admin fixing OUR quality miss must never spend it).
 *
 * The proof below is arithmetic, not "very unlikely to collide":
 *
 * Every seed a customer re-roll can EVER produce for a given cut is
 *   STILL_SEED + cutIndex*100 + REROLL_SEED_BAND*rerollCount + take*1000 + attempt*7919
 * with cutIndex in [0, NUM_CUTS-1], rerollCount in [0, STORYBOARD_REROLL_CAP]
 * (app/api/orders/reroll-cut/route.ts's guarded `updateMany` makes it
 * structurally impossible for storyboardRerollCount to ever exceed
 * STORYBOARD_REROLL_CAP — see that route's comment), take in
 * [0, TAKES_PER_CUT-1], attempt in [0, MAX_TAKE_REROLLS]. The maximum
 * possible OFFSET above STILL_SEED across that entire space is
 * MAX_CUSTOMER_SEED_OFFSET below — derived FROM the exact same constants the
 * customer path uses, so it cannot silently go stale if any of them change.
 *
 * ADMIN_REROLL_SEED_OFFSET is then set to MAX_CUSTOMER_SEED_OFFSET plus one
 * full extra REROLL_SEED_BAND of headroom, so the SMALLEST seed an admin
 * re-roll can EVER produce (adminRerollCount=0, cutIndex=0, take=0,
 * attempt=0) is still strictly larger than the LARGEST seed a customer
 * re-roll can ever produce. The two ranges are disjoint by inequality between
 * two closed-form maxima — not a probability that happens to be small.
 * ADMIN_REROLL_SEED_BAND then keeps two DIFFERENT admin re-rolls (varying
 * adminRerollCount) apart from each other by the identical reasoning
 * REROLL_SEED_BAND already uses for two different customer re-rolls.
 */
const MAX_CUSTOMER_SEED_OFFSET =
  (NUM_CUTS - 1) * 100 +
  REROLL_SEED_BAND * STORYBOARD_REROLL_CAP +
  (TAKES_PER_CUT - 1) * 1000 +
  MAX_TAKE_REROLLS * 7919; // = 3,018,338 with today's constants (5*100 + 1_000_000*3 + 2*1000 + 2*7919)

const ADMIN_REROLL_SEED_OFFSET = MAX_CUSTOMER_SEED_OFFSET + REROLL_SEED_BAND; // strictly above the customer ceiling, with a full band of margin
const ADMIN_REROLL_SEED_BAND = REROLL_SEED_BAND; // same per-reroll spacing as the customer band, same no-collision argument

/**
 * Admin-only counterpart to rerollSeedBase — see the block comment above for
 * the disjointness proof. `adminRerollCount` is the ORDER-WIDE, atomically-
 * incremented `Order.adminRerollCount` column (never storyboardRerollCount),
 * AFTER increment — mirroring how rerollSeedBase consumes
 * storyboardRerollCount after ITS atomic increment.
 */
export function adminRerollSeedBase(cutIndex: number, adminRerollCount: number): number {
  return STILL_SEED + ADMIN_REROLL_SEED_OFFSET + cutIndex * 100 + ADMIN_REROLL_SEED_BAND * adminRerollCount;
}

// FILM-QUALITY-V3-SPEC.md §4.2: generateTakeOnce's prompt had no mouth/tongue
// direction at all, so the model defaulted to "a happy dog" = tongue out —
// correct for `playful`, wrong for every other world/personality (the owner's
// complaint was specifically a 1980s citypop "cool, composed" world reading as
// goofy instead). `playful` is the only personality this should be skipped
// for; every other value, INCLUDING `null` (a custom/Director's Cut order has
// no personality field at all), gets the closed-mouth direction — a custom
// order has no reason to default to the "playful" look just because it has
// no explicit personality.
const CLOSED_MOUTH_DIRECTIVE = "mouth closed, no lolling tongue, composed expression";

/** Per FILM-QUALITY-V3-SPEC.md §4.2 — see CLOSED_MOUTH_DIRECTIVE above. */
export function expressionDirective(personality: string | null): string {
  return personality === "playful" ? "" : CLOSED_MOUTH_DIRECTIVE;
}

function assertEnv(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`${name} is not set`);
  return v;
}

/* ------------------------------------------------------------------ */
/* Per-order LoRA training (LORA-STORYBOARD-SPEC.md §2.1, §2.7)         */
/*                                                                      */
/* NOT a stage of runStillsGeneration below — measured at ~45 minutes   */
/* (n=1, fal queue time included), which is why §2.7 pulls it into its  */
/* own upstream Trigger.dev task (trigger/train-lora.ts) instead of     */
/* running it in-process here. The functions in this section are used  */
/* by runLoraTraining (that task's core logic, further down this file)  */
/* and by kickLoraTraining's local-dev fallback — never by              */
/* runStillsGeneration itself.                                          */
/* ------------------------------------------------------------------ */

const LORA_TRAINER_MODEL = "fal-ai/flux-2-trainer-v2";
// fal-ai/flux-2/lora/edit — the single-call take generator (B1, §2.2).
export const LORA_EDIT_MODEL = "fal-ai/flux-2/lora/edit";
// §1.7's camyu measurement, reused verbatim (not re-derived here): the
// trainer's own recommendation is higher, but this is what actually validated
// during the bake-off.
const LORA_TRAIN_STEPS = 1500;
export const LORA_SCALE = 1.0;
// §4.1/§1.8: the model's own default, kept EXPLICIT (not omitted) so a future
// edit can see, in code, that this is a deliberate ceiling — raising it made
// the render more detailed but swapped in a visibly different dog in the
// owner's own comparison (§1.8's "C" arm). Never raise this.
export const LORA_GUIDANCE_SCALE = 2.5;
// §2.2 trap: this MUST be an explicit {width,height} object. The preset name
// "landscape_16_9" silently downgrades this exact endpoint to 1024x576 — an
// entire comparison run was measured at the wrong resolution before that was
// caught (§2.2/§2.4). 2048x1152 is B1's native ceiling (nano-banana's
// 2752x1536 was higher — see §2.4 for why that drop doesn't reach the poster).
export const B1_IMAGE_SIZE = { width: 2048, height: 1152 } as const;

// §4.1: a POSITIVE anatomy directive (this endpoint has no negative-prompt
// input), added to every take regardless of which generation path produced
// it. LORA-STORYBOARD-SPEC.md §1.8 could NOT prove this changes the limb-
// breakage rate at n=6 — it is included anyway because it costs nothing to
// add and cannot make anatomy worse. The actual backstop is the anatomy GATE
// (scoreAnatomy, lib/identity.ts) inside generateGatedTake below, §4.2 — this
// string is the cheap half of that fix, not the guaranteed half.
const ANATOMY_DIRECTIVE =
  "Anatomically correct dog: exactly four legs — two front legs and two hind legs — each attached to the body in the right place, one paw per leg. No extra limbs, no missing limbs, no duplicated or floating paws, no tangled or merged legs. The body under the suit is a single coherent dog.";

/**
 * Order-unique trigger word the LoRA is trained on and every B1 take prompt
 * must reuse verbatim. Deliberately NOT a breed name or anything English/
 * dictionary — a rare string the base model has no prior for, so whatever it
 * comes to mean is entirely defined by the training photos (§2.1). Derived
 * from the order id (not random) so it's reproducible without persisting it
 * separately from loraUrl, and stable across a retried training run.
 */
function loraTriggerWord(orderId: string): string {
  return `mtpet${orderId.replace(/[^a-zA-Z0-9]/g, "").slice(0, 16)}`;
}

/** Lazily built CRC-32 table (IEEE 802.3 polynomial, reflected: 0xEDB88320). */
let crcTable: Uint32Array | null = null;

/**
 * CRC-32 for the ZIP writer below.
 *
 * Hand-rolled rather than `import { crc32 } from "node:zlib"`, which is what
 * this used at first: it works locally, but Trigger.dev's deploy refused every
 * task file with "The requested module 'node:zlib' does not provide an export
 * named 'crc32'". `zlib.crc32` only landed in Node 20.15/22.2 and is not
 * visible as an ESM named export in the environment that bundles these tasks —
 * so the one line that made the ZIP writer "dependency-free" was itself an
 * undeclared dependency on a Node version we don't control.
 *
 * Twenty lines of table-driven CRC has no such assumption. Verified byte-for-
 * byte against zlib's own crc32 on the training photos before replacing it.
 */
function crc32(buf: Buffer): number {
  if (!crcTable) {
    crcTable = new Uint32Array(256);
    for (let i = 0; i < 256; i++) {
      let c = i;
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      crcTable[i] = c >>> 0;
    }
  }
  let crc = 0xffffffff;
  for (let i = 0; i < buf.length; i++) crc = crcTable[(crc ^ buf[i]) & 0xff] ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

/**
 * Minimal ZIP writer (STORE method — no compression, the training photos are
 * already JPEG/PNG so compressing again buys nothing), paired with the
 * hand-rolled crc32 above. Deliberately dependency-free: this repo has no zip
 * library, and the one system `zip` binary this dev machine happens to have is
 * not a dependency Trigger.dev's cloud machines are guaranteed to ship (unlike
 * ffmpeg, which trigger.config.ts explicitly installs via a build extension) —
 * pure JS works identically in local dev, Vercel and Trigger.dev with nothing
 * extra to provision. See crc32's comment for why even a Node builtin was too
 * strong an assumption here.
 */
function zipStore(entries: { name: string; data: Buffer }[]): Buffer {
  const localParts: Buffer[] = [];
  const centralParts: Buffer[] = [];
  let offset = 0;
  const now = new Date();
  const dosTime = ((now.getHours() << 11) | (now.getMinutes() << 5) | (now.getSeconds() >> 1)) & 0xffff;
  const dosDate = (((Math.max(0, now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate())) & 0xffff;

  for (const { name, data } of entries) {
    const nameBuf = Buffer.from(name, "utf8");
    const crc = crc32(data) >>> 0;

    const localHeader = Buffer.alloc(30);
    localHeader.writeUInt32LE(0x04034b50, 0);
    localHeader.writeUInt16LE(20, 4); // version needed to extract
    localHeader.writeUInt16LE(0, 6); // flags
    localHeader.writeUInt16LE(0, 8); // method: store
    localHeader.writeUInt16LE(dosTime, 10);
    localHeader.writeUInt16LE(dosDate, 12);
    localHeader.writeUInt32LE(crc, 14);
    localHeader.writeUInt32LE(data.length, 18); // compressed size
    localHeader.writeUInt32LE(data.length, 22); // uncompressed size
    localHeader.writeUInt16LE(nameBuf.length, 26);
    localHeader.writeUInt16LE(0, 28); // extra field length
    localParts.push(localHeader, nameBuf, data);

    const centralHeader = Buffer.alloc(46);
    centralHeader.writeUInt32LE(0x02014b50, 0);
    centralHeader.writeUInt16LE(20, 4); // version made by
    centralHeader.writeUInt16LE(20, 6); // version needed to extract
    centralHeader.writeUInt16LE(0, 8); // flags
    centralHeader.writeUInt16LE(0, 10); // method: store
    centralHeader.writeUInt16LE(dosTime, 12);
    centralHeader.writeUInt16LE(dosDate, 14);
    centralHeader.writeUInt32LE(crc, 16);
    centralHeader.writeUInt32LE(data.length, 20);
    centralHeader.writeUInt32LE(data.length, 24);
    centralHeader.writeUInt16LE(nameBuf.length, 28);
    centralHeader.writeUInt16LE(0, 30); // extra field length
    centralHeader.writeUInt16LE(0, 32); // comment length
    centralHeader.writeUInt16LE(0, 34); // disk number start
    centralHeader.writeUInt16LE(0, 36); // internal attrs
    centralHeader.writeUInt32LE(0, 38); // external attrs
    centralHeader.writeUInt32LE(offset, 42); // relative offset of local header
    centralParts.push(centralHeader, nameBuf);

    offset += localHeader.length + nameBuf.length + data.length;
  }

  const centralDirStart = offset;
  const centralDirBuf = Buffer.concat(centralParts);
  const endRecord = Buffer.alloc(22);
  endRecord.writeUInt32LE(0x06054b50, 0);
  endRecord.writeUInt16LE(0, 4); // disk number
  endRecord.writeUInt16LE(0, 6); // disk with central dir
  endRecord.writeUInt16LE(entries.length, 8);
  endRecord.writeUInt16LE(entries.length, 10);
  endRecord.writeUInt32LE(centralDirBuf.length, 12);
  endRecord.writeUInt32LE(centralDirStart, 16);
  endRecord.writeUInt16LE(0, 20); // comment length

  return Buffer.concat([...localParts, centralDirBuf, endRecord]);
}

/** Downloads every training photo and packs them into one in-memory ZIP for the trainer's `image_data_url`. */
async function buildTrainingZip(photoUrls: string[]): Promise<Buffer> {
  const entries = await Promise.all(
    photoUrls.map(async (url, i) => {
      const resolved = publicUrl(url);
      const res = await fetch(resolved);
      if (!res.ok) throw new Error(`training photo download failed ${res.status}: ${resolved}`);
      const data = Buffer.from(await res.arrayBuffer());
      const ext = new URL(resolved).pathname.match(/\.(\w+)$/)?.[1]?.toLowerCase() || "jpg";
      return { name: `photo${i}.${ext}`, data };
    })
  );
  return zipStore(entries);
}

/**
 * Trains ONE LoRA on this order's own photos (§2.1). Never throws: any
 * failure (download, zip, upload, the trainer call itself, or a response
 * missing a LoRA file) is caught and logged, returning `null` so the caller
 * falls back to the pre-B1 nano-banana costume chain for every take in this
 * order (HARD CONSTRAINT: an order must never die because LoRA training
 * failed).
 *
 * §2.7: this alone measured at ~45 minutes (n=1, fal queue time included) —
 * far longer than this spec originally assumed. That is why it is called from
 * `runLoraTraining` (below), which is invoked ONLY by trigger/train-lora.ts's
 * task (production) or kickLoraTraining's local-dev branch — NEVER from
 * inside runStillsGeneration/the "generate-stills" task. Splitting it into
 * its own task means a stills-side failure (a bad VLM response, a fal
 * hiccup) can retry freely without ever repeating this 45-minute run; folding
 * it into the same task as stills generation would mean any transient
 * failure downstream throws away the training run right along with it.
 *
 * Callers MUST only invoke this when the order has no `loraUrl` yet — see
 * `runLoraTraining`'s reuse check, which is the ONLY thing standing between
 * "trained once per order" and a double-train if the training task itself is
 * retried. reshootCutStill and rerollCutTakes (both far downstream, at Gate 1
 * re-roll / Gate 2 re-shoot time) read `order.loraUrl`/`loraTriggerWord` off
 * the order record instead of ever calling this again.
 */
async function trainPetLora(
  orderId: string,
  photoUrls: string[]
): Promise<{ url: string; triggerWord: string } | null> {
  try {
    if (photoUrls.length === 0) throw new Error("no photos to train on");
    const triggerWord = loraTriggerWord(orderId);
    console.log(`[lora] training LoRA order=${orderId} trigger=${triggerWord} photos=${photoUrls.length}`);
    const zipBuffer = await buildTrainingZip(photoUrls);
    const zipFile = new File([new Uint8Array(zipBuffer)], `${orderId}-training.zip`, { type: "application/zip" });
    const zipUrl = await fal.storage.upload(zipFile);
    const t = await fal.subscribe(LORA_TRAINER_MODEL, {
      input: {
        image_data_url: zipUrl,
        // §2.1 trap: NO breed name in this caption. Naming the breed would
        // summon the base model's breed prototype right back — the exact
        // drift training a LoRA exists to eliminate (§1.1).
        default_caption: `photo of ${triggerWord}, a small dog`,
        steps: LORA_TRAIN_STEPS,
      },
      abortSignal: falDeadline(FAL_TRAIN_CAP_MS),
    });
    const d = t.data as { diffusers_lora_file?: { url?: string }; lora_file?: { url?: string } };
    const loraUrl = d.diffusers_lora_file?.url ?? d.lora_file?.url;
    if (!loraUrl) throw new Error(`trainer returned no LoRA file: ${JSON.stringify(t.data).slice(0, 300)}`);
    console.log(`[lora] trained order=${orderId}: ${loraUrl}`);
    return { url: loraUrl, triggerWord };
  } catch (e) {
    console.warn(
      `[lora] order=${orderId}: LoRA training failed — every take in this order falls back to the pre-B1 nano-banana costume chain (this order's likeness will be the OLD quality, not B1's)`,
      e
    );
    return null;
  }
}

/**
 * §2.7 — the core logic of the "train-pet-lora" Trigger.dev task
 * (trigger/train-lora.ts): reuse-or-train, then persist. This is the ONLY
 * function in the codebase that calls `trainPetLora`, and it is itself called
 * from exactly two places: trigger/train-lora.ts's task (production) and
 * kickLoraTraining's local-dev branch (below) — never from
 * runStillsGeneration, which only ever reads the fields this persists.
 *
 * Reuse check first: an order that already carries `loraUrl`/`loraTriggerWord`
 * skips training entirely. This is what makes "trained once per order" hold
 * even if the train-pet-lora TASK ITSELF is retried by Trigger.dev (e.g. the
 * final `prisma.order.update` below throws and the whole run is retried) —
 * the retry reads the order fresh, sees the field already set, and skips
 * straight past training.
 *
 * Deliberately does NOT trigger the stills task itself — that is the caller's
 * job (trigger/train-lora.ts's `run`, or kickLoraTraining's local-dev
 * branch), specifically so the "always trigger stills, whether this
 * succeeded or not" logic lives in ONE place per environment rather than
 * being duplicated here.
 */
export async function runLoraTraining(order: Order): Promise<void> {
  if (order.loraUrl && order.loraTriggerWord) {
    console.log(`[lora] reuse cached LoRA order=${order.id} (skip training)`);
    return;
  }
  const trained = await trainPetLora(order.id, order.uploadedPhotoUrls);
  if (trained) {
    await prisma.order.update({
      where: { id: order.id },
      data: { loraUrl: trained.url, loraTriggerWord: trained.triggerWord },
    });
  }
  // `trained === null` here means training failed and trainPetLora already
  // logged why — nothing more to do: loraUrl stays null, and every downstream
  // take falls back to the pre-B1 chain (generateTakeOnce's `lora` param
  // ends up undefined). This function does not re-throw that failure.
}

/**
 * Stage 0 — one VLM pass over the uploads that both (a) extracts the pet's
 * distinguishing features and (b) auto-sorts the photos by angle, so the
 * cleanest FRONT-FACING shot seeds the identity portrait.
 * No per-photo labeling asked of the customer (auto-detect, not manual).
 */
async function analyzePhotos(
  photoUrls: string[]
): Promise<{ description: string; bestFrontalIndex: number; hasFrontal: boolean }> {
  const n = Math.min(photoUrls.length, 6);
  const r = await fal.subscribe(VISION_MODEL, {
    input: {
      model: VISION_LLM,
      image_urls: photoUrls.slice(0, n),
      prompt:
        `These ${n} photos (indexed 0-${n - 1}) show ONE pet. Reply with ONLY minified JSON, no prose:\n` +
        `{"description":"<one dense sentence, max 70 words: exact coat colors and where they appear, fur texture/length/haircut, face shape, eye color/shape, nose, muzzle/beard/eyebrow markings, body build — features only, no name>",` +
        // These four drift the most and owners notice them, so pin each one
        // explicitly and inject verbatim into every generation prompt.
        `"mouth":"<color of the inside of the mouth/tongue and lips, e.g. pink tongue, black lips>",` +
        `"tail":"<tail length and shape, e.g. short docked stub, long feathered, curled over back>",` +
        `"ears":"<ear carriage exactly, e.g. floppy triangular drop ears, upright pointed, semi-erect>",` +
        // IDENTITY-FIDELITY-SPEC.md §1.3/§2.3: "coat colors / fur texture /
        // face shape" alone tends to describe the BREED, not the individual —
        // a generic sentence about a schnauzer's markings is true of
        // thousands of schnauzers. This field explicitly asks for the ways
        // THIS pet deviates from a breed-standard example, which is exactly
        // the information a model needs to avoid drifting back toward the
        // generic breed prototype (the owner's actual complaint: a soft,
        // overgrown, round-faced individual rendered as a neatly-groomed,
        // standard-proportioned example of the breed).
        `"distinguishingFromBreed":"<the 2-3 most important ways this INDIVIDUAL differs from a generic/breed-standard example of the same breed (not a breed description) — MUST cover: (1) current grooming/coat-length state, e.g. freshly trimmed and neat vs overgrown/shaggy and where (2) face shape vs breed-standard, e.g. rounder/softer or more angular/sharp (3) eye size impression vs breed-standard, e.g. proportionally larger/softer-looking or smaller>",` +
        `"best_frontal_index":<index of the photo with the clearest, sharpest FRONT-FACING view of the face, or -1 if none is front-facing>}`,
    },
    abortSignal: falDeadline(FAL_VISION_CAP_MS),
  });
  const raw = String((r.data as { output?: string; text?: string })?.output ?? (r.data as { text?: string })?.text ?? "");
  try {
    const json = JSON.parse(raw.slice(raw.indexOf("{"), raw.lastIndexOf("}") + 1));
    const base = String(json.description ?? "").trim().slice(0, 480);
    const idx = Number.isInteger(json.best_frontal_index) ? json.best_frontal_index : -1;
    if (!base) throw new Error("empty description");
    // Pin the details owners notice most, verbatim, into the description that
    // flows to every downstream prompt (portrait, hero sheet, stills).
    const locked: string[] = [];
    if (json.mouth) locked.push(`mouth/tongue: ${String(json.mouth).trim()}`);
    if (json.tail) locked.push(`tail: ${String(json.tail).trim()}`);
    if (json.ears) locked.push(`ears: ${String(json.ears).trim()}`);
    let desc = locked.length
      ? `${base} MUST MATCH EXACTLY — ${locked.join("; ")}.`
      : base;
    // §2.3/§1.3: pinned separately from the "MUST MATCH EXACTLY" list above —
    // this isn't a literal detail like tongue color, it's an instruction NOT
    // to normalize this individual back toward the breed prototype, which is
    // the exact drift the owner's real-photo comparison caught.
    if (json.distinguishingFromBreed) {
      desc += ` Do NOT idealize toward a generic breed-standard look — this individual's actual grooming/face/eyes: ${String(json.distinguishingFromBreed).trim()}.`;
    }
    return { description: desc, bestFrontalIndex: idx >= 0 && idx < n ? idx : 0, hasFrontal: idx >= 0 };
  } catch {
    // Fallback: use whatever text came back as the description, keep order.
    const desc = raw.replace(/[{}]/g, " ").trim().slice(0, 500);
    if (!desc) throw new Error("vision model returned nothing usable");
    return { description: desc, bestFrontalIndex: 0, hasFrontal: false };
  }
}

/**
 * Stage 1 — neutral close-up that locks the face before any transformation.
 *
 * `seed` lets generateGatedPortrait (below) re-roll a drifted attempt on a
 * fresh seed, the same pattern generateTakeOnce/generateGatedTake already use
 * for stage 3.
 *
 * §2.4: this is the single highest-leverage place in the whole pipeline to
 * fix grooming drift — the portrait is the anchor for the hero sheet AND all
 * 18 takes, so if the portrait "tidies up" the pet's actual coat, every
 * downstream generation inherits that tidied-up look no matter how good the
 * take-level gate (§2.1) is. IDENTITY_RULES already said "do NOT groom them
 * differently", but the owner's actual complaint (soft, overgrown topknot
 * rendered as neatly trimmed) shows that instruction wasn't concrete enough
 * for the model to act on, so it's restated here in specific, literal terms.
 */
async function generateIdentityPortrait(
  photoUrls: string[],
  description: string,
  seed: number
): Promise<string> {
  const r = await fal.subscribe(EDIT_MODEL, {
    input: {
      prompt: `Photorealistic studio portrait photograph of this exact pet from the reference photos: ${description}. Head-and-chest close-up looking toward the camera, plain dark studio background, soft flattering key light, tack-sharp focus on the face. No clothing, no accessories. Reproduce this individual's CURRENT fur exactly as it appears in the reference photos — if it looks overgrown, shaggy, uneven, or due for a trim, render it exactly that overgrown/shaggy/uneven; do NOT trim, shorten, neaten, straighten, or otherwise groom it into a tidier or more "finished" look than the references actually show. ${IDENTITY_RULES}`,
      image_urls: photoUrls,
      num_images: 1,
      resolution: "2K",
      aspect_ratio: "3:4",
      output_format: "png",
      seed,
    },
    abortSignal: falDeadline(FAL_IMAGE_CAP_MS),
  });
  const url = (r.data as { images?: { url?: string }[] })?.images?.[0]?.url;
  if (!url) throw new Error("identity portrait result missing image url");
  return url;
}

// Distinct seed family from STILL_SEED (stage 3 takes, below) and
// film-pipeline.ts's END_FRAME_SEED, so a shared order can never have a
// portrait re-roll land on the same numeric seed as a storyboard take or end
// frame (same "keep the bands disjoint" reasoning as rerollSeedBase's
// comment, even though a seed collision here couldn't actually reproduce a
// duplicate image — the portrait prompt is entirely different from a take's
// prompt — this just keeps every generation's seed provenance unambiguous
// when read out of logs).
const PORTRAIT_SEED = 50_000;
// Same reroll budget as a storyboard take (MAX_TAKE_REROLLS) — no reason for
// a stingier retry budget at the one gate everything downstream depends on.
const MAX_PORTRAIT_REROLLS = 2;
// §2.4: same bar as a take (IDENTITY_THRESHOLD) — the portrait is the anchor
// for every take, so it has no business clearing a LOWER bar than the takes
// it anchors.
const PORTRAIT_IDENTITY_THRESHOLD = IDENTITY_THRESHOLD;

/**
 * §2.4 — gate the identity portrait itself against the customer's real
 * photo before anything downstream (hero sheet, all 18 takes) is generated
 * from it. Previously there was NO gate here at all: the portrait was
 * generated once and trusted, so a single bad portrait-generation silently
 * poisoned the entire order. Re-rolls on a fresh seed like generateGatedTake;
 * returns the best attempt regardless so an order is never blocked here.
 *
 * `realPhotoUrl` can be undefined only if the order has no usable uploaded
 * photo at all — uploads are mandatory, so this is a defensive branch, not
 * the intended path. Per HARD CONSTRAINT #3 (never fail an order over this
 * fix), that case skips the gate entirely and generates one ungated
 * portrait — today's pre-fix behavior — rather than throwing.
 */
async function generateGatedPortrait(
  photoUrls: string[],
  description: string,
  realPhotoUrl: string | undefined,
  orderId: string
): Promise<string> {
  if (!realPhotoUrl) {
    console.warn(
      `[stills] order=${orderId}: no real photo available for portrait identity gate — generating ungated portrait (pre-fix behavior)`
    );
    return generateIdentityPortrait(photoUrls, description, PORTRAIT_SEED);
  }
  let best = "";
  let bestScore = -1;
  for (let attempt = 0; attempt <= MAX_PORTRAIT_REROLLS; attempt++) {
    const seed = PORTRAIT_SEED + attempt * 7919; // 7919 (prime): same re-roll-offset convention as generateGatedTake
    const url = await generateIdentityPortrait(photoUrls, description, seed);
    const score = await scoreIdentity(realPhotoUrl, url);
    console.log(`[stills] portrait attempt ${attempt} order=${orderId}: identity ${score} (vs real photo)`);
    if (score > bestScore) {
      bestScore = score;
      best = url;
    }
    if (score >= PORTRAIT_IDENTITY_THRESHOLD) return url;
  }
  console.warn(
    `[stills] order=${orderId}: best portrait identity ${bestScore} (< ${PORTRAIT_IDENTITY_THRESHOLD}), using best attempt — every downstream hero sheet/take will inherit this drift`
  );
  return best;
}

/**
 * Stage 2 — hero sheet: the pet in the film's LOCKED costume, neutral pose.
 * Generated once and referenced by every take, so costume, tail and face stay
 * identical across cuts (the fix for shot-to-shot drift).
 */
async function generateHeroSheet(refs: string[], description: string, costume: string): Promise<string> {
  const r = await fal.subscribe(EDIT_MODEL, {
    input: {
      prompt: `Full-body character reference of this exact pet from the reference images — ${description} — ${costume}. Standing in a neutral three-quarter pose, facing the camera, plain neutral studio background, even soft lighting, the whole body and tail visible and in focus. This is the definitive costumed look of the character. ${STYLE_RULES} ${IDENTITY_RULES}`,
      image_urls: refs,
      num_images: 1,
      resolution: "2K",
      // 16:9 — these stills ARE the film frames (the master trailer is 16:9),
      // so they must be shot landscape or the assembly crop lops off top/bottom.
      aspect_ratio: "16:9",
      output_format: "png",
    },
    abortSignal: falDeadline(FAL_IMAGE_CAP_MS),
  });
  const url = (r.data as { images?: { url?: string }[] })?.images?.[0]?.url;
  if (!url) throw new Error("hero sheet missing url");
  return url;
}

/**
 * One raw 16:9 cinematic take — same character, same costume, one scene, one
 * seed.
 *
 * §2.2 (B1, primary path): when this order has a trained LoRA, the whole take
 * collapses to ONE fal-ai/flux-2/lora/edit call — the LoRA's weights carry
 * this pet's identity, so `image_urls` carries ONLY the costume reference
 * sheet, never the real photo/portrait chain. LORA-STORYBOARD-SPEC.md §1.2-
 * 1.3 measured why the old two-model chain (a model that doesn't know this
 * pet re-drawing it from a reference) cannot be prompted into working: any
 * model asked to REDRAW an unfamiliar animal regresses it toward its breed
 * average, and that happens exactly when composition changes — which a real
 * trailer's varied framing requires on every cut. A trained LoRA sidesteps
 * this because there is no redraw step to regress during.
 *
 * `IDENTITY_RULES` is deliberately NOT included in the B1 branch (§2.2 trap):
 * those rules exist to argue a generic model out of drifting toward a breed
 * prototype it already knows too well. A model that has been trained on this
 * specific pet already agrees — restating the rules only adds noise to a
 * conversation that's already settled. Likewise the trigger word's use here
 * never names the breed (§2.1) for the same reason `default_caption` doesn't.
 *
 * Falls back to the pre-B1 nano-banana costume chain (this file's original
 * implementation, unchanged) whenever no LoRA is available for this order —
 * training failed, or (shouldn't happen; uploads are mandatory) there were no
 * photos to train on. `hasRealPhotoFirst` only matters to this fallback
 * branch: `refs[0]` is the customer's real photo whenever available
 * (IDENTITY-FIDELITY-SPEC.md §2.2 — see generateGatedTake's callers), so the
 * prompt's role directive matches what's actually in position 0.
 */
export async function generateTakeOnce(
  refs: string[],
  hasRealPhotoFirst: boolean,
  description: string,
  costume: string,
  scene: string,
  framing: string,
  expression: string,
  seed: number,
  lora: { url: string; triggerWord: string } | undefined,
  costumeSheetUrl: string | undefined
): Promise<string> {
  if (lora && costumeSheetUrl) {
    const prompt =
      `A cinematic live-action film still of ${lora.triggerWord}, a small dog, ${costume}, ${scene}. ${framing}.` +
      `${expression ? ` ${expression}.` : ""} The reference image is this film's costume reference sheet — take ONLY the costume/outfit shown in it exactly, ignoring its background, pose and lighting. This exact animal's identity comes from the model itself, not from the reference image. ` +
      `${ANATOMY_DIRECTIVE} One cinematic live-action film still, blockbuster cinematography, dramatic lighting, shallow depth of field, film grain. ${STYLE_RULES}`;
    const r = await fal.subscribe(LORA_EDIT_MODEL, {
      input: {
        prompt,
        image_urls: [costumeSheetUrl],
        loras: [{ path: lora.url, scale: LORA_SCALE }],
        num_images: 1,
        image_size: B1_IMAGE_SIZE, // §2.2 trap: explicit object, never a preset name
        output_format: "png",
        guidance_scale: LORA_GUIDANCE_SCALE, // §4.1/§1.8: never above the 2.5 default
        seed,
      },
      abortSignal: falDeadline(FAL_IMAGE_CAP_MS),
    });
    const url = (r.data as { images?: { url?: string }[] })?.images?.[0]?.url;
    if (!url) throw new Error("B1 take result missing url");
    return url;
  }

  // Fallback: pre-B1 nano-banana costume chain, verbatim (unchanged from
  // before this feature) except for the added ANATOMY_DIRECTIVE (§4.1, which
  // applies to every take regardless of generation path) and an explicit
  // "ignore its background, pose and lighting" clause on the costume-sheet
  // role (§3's costume-consistency fix).
  const roleDirective = hasRealPhotoFirst
    ? "The FIRST reference image is a real photo of this individual pet — its definitive REAL-WORLD look: match its exact face, fur colors and markings, proportions, and current grooming/coat length. The SECOND reference image is the film's costume reference sheet — match ONLY the costume/outfit shown in it exactly, ignoring its background, pose and lighting; it is not the identity anchor, ignore any difference in its fur styling."
    : "The FIRST reference image is the definitive look of this character — match its costume, fur colors and markings, tail and face EXACTLY."; // fallback: no real photo available for this order, see generateGatedTake
  const r = await fal.subscribe(EDIT_MODEL, {
    input: {
      prompt: `${roleDirective} This exact pet (${description}), ${costume}, ${scene}. ${framing}.${expression ? ` ${expression}.` : ""} ${ANATOMY_DIRECTIVE} One cinematic live-action film still, unmistakably the same individual pet, same outfit as the reference, blockbuster cinematography, dramatic lighting, shallow depth of field, film grain. ${STYLE_RULES} ${IDENTITY_RULES}`,
      image_urls: refs,
      num_images: 1,
      resolution: "2K",
      // 16:9 — this take becomes a film frame; the master trailer is 16:9.
      aspect_ratio: "16:9",
      output_format: "png",
      seed,
    },
    abortSignal: falDeadline(FAL_IMAGE_CAP_MS),
  });
  const url = (r.data as { images?: { url?: string }[] })?.images?.[0]?.url;
  if (!url) throw new Error("take result missing url");
  return url;
}

/**
 * One gated take: render, score against the customer's REAL photo AND check
 * anatomy, re-roll (with a fresh seed) until BOTH clear or we run out of
 * attempts. Returns the best-identity attempt regardless, so a cut always has
 * three takes to choose from.
 *
 * §2.1/IDENTITY-FIDELITY-SPEC.md §1.1: the gate used to score against the
 * generated portrait (`scoreIdentity(portraitUrl, url)`), even though its own
 * prompt says "Image 1 is the REAL pet" — a lie, since the portrait is
 * AI-generated. That let a take drift further from the actual dog while
 * scoring HIGHER, as long as it drifted the same direction the portrait
 * already had (scores of 80-85 with no real resemblance were that arithmetic
 * working as written). Gating on `realPhotoUrl` instead makes that prompt
 * line true and makes the gate measure the thing the product actually needs:
 * does this take look like the customer's dog.
 *
 * `portraitUrl` is kept as a required param (not folded away) purely as the
 * `realPhotoUrl` fallback target — see below — not because it's scored
 * against.
 *
 * `realPhotoUrl` can be undefined only if the order somehow has no usable
 * uploaded photo — uploads are mandatory, so this shouldn't happen. Per HARD
 * CONSTRAINT #3 this must never become a new failure mode: fall back to
 * gating against the portrait (the exact pre-fix behavior) and log loudly so
 * it surfaces as an anomaly rather than silently regressing.
 *
 * `lora`/`costumeSheetUrl` (LORA-STORYBOARD-SPEC.md §2.2, §4.2) are threaded
 * straight through to generateTakeOnce (`lora` undefined -> the pre-B1
 * fallback chain there) and are ORTHOGONAL to the identity gate below: B1 or
 * not, every take is still scored against the same real photo, at the same
 * threshold, plus the anatomy check (scoreAnatomy) added by §4.2 — the
 * anatomy gate runs in EXACTLY the same place, for EXACTLY the same reason,
 * regardless of which model produced the candidate. Both checks run in
 * parallel per attempt (one extra VLM call per attempt, not per retry chain)
 * so this stays as cheap as a single extra image per judgment call.
 */
async function generateGatedTake(
  refs: string[],
  hasRealPhotoFirst: boolean,
  description: string,
  costume: string,
  scene: string,
  framing: string,
  expression: string,
  realPhotoUrl: string | undefined,
  portraitUrl: string,
  baseSeed: number,
  label: string,
  lora: { url: string; triggerWord: string } | undefined,
  costumeSheetUrl: string | undefined
): Promise<string> {
  // The re-roll loop AND the scoring that used to live here are both gone,
  // because a human is already doing this job. Every storyboard sits in the
  // admin queue (status IMAGE_GENERATING, see adminRerollCount in
  // prisma/schema.prisma) and is reviewed BEFORE the customer ever sees it —
  // and an admin re-roll there costs one still, the same as a retry here,
  // spent on a cut a person actually judged instead of on a VLM's number.
  //
  // The scoring went with it because nothing could read it. Take scores were
  // never persisted and no admin screen renders them — StoryboardReviewPanel,
  // the screen where the storyboard is actually approved, has no identity or
  // anatomy field at all. They reached the Trigger.dev log and stopped there,
  // at 2 vision calls x 18 takes = 36 per order. (The CLIP score is a
  // different thing and is still produced: it IS displayed, in the Gate-2
  // drift table — see generateGatedClip in film-pipeline.ts.)
  //
  // For the same reason, how often the retry used to fire is NOT KNOWN and
  // nothing here should be read as claiming otherwise — there is no record
  // left to count. What IS known is that the bar was IDENTITY_THRESHOLD = 50
  // out of 100, low enough that clearing it was never much of a claim.
  //
  // `realPhotoUrl` / `portraitUrl` are now unused. They are kept in the
  // signature deliberately: this function takes 13 POSITIONAL arguments and
  // has four call sites, so dropping two of them is a silent-miswiring
  // hazard out of all proportion to the tidiness gained — and they are
  // exactly what a future scoring pass would need back.
  //
  // MAX_TAKE_REROLLS stays defined in this file even though nothing loops on
  // it now: it is not dead code, it is a RESERVED seed band.
  // scripts/test-safety-net.ts imports it to prove that a customer's re-roll
  // can never redraw a seed this stage already used, and this generator still
  // only ever takes attempt 0 — so the reservation, and the proof, hold.
  const seed = baseSeed; // baseSeed + 0 * 7919 — see MAX_TAKE_REROLLS note above.
  return generateTakeOnce(refs, hasRealPhotoFirst, description, costume, scene, framing, expression, seed, lora, costumeSheetUrl);
}

/**
 * One Gate-1 take option — TWO urls, never one, so the data model can't be
 * ambiguous about which is safe to hand the customer (PRICING-PRODUCT-V2-SPEC.md
 * §3.5(C)):
 *   preview — watermarked + downscaled (lib/watermark.ts). The ONLY url that
 *             may ever reach the customer's browser before completion.
 *   clean   — the full-res, unwatermarked fal take. Never rendered to the
 *             customer at Gate 1; this is what chosenStills carries forward
 *             and what the film pipeline actually animates.
 * `storyboardOptions` is Prisma `Json?` (no schema change for this feature),
 * so this shape lives entirely inside that JSON blob — see normalizeStoryboard
 * below for how a PRE-this-feature row (options as plain strings) reads back.
 */
export type StillOption = { preview: string; clean: string };

export type StoryboardCut = { scene: string; options: StillOption[] };

/** Intermediate shape used while stills are being generated, before the
 *  watermarking pass runs — options are still bare clean urls here. */
type CleanStoryboardCut = { scene: string; options: string[] };

/**
 * Defensive reader for order.storyboardOptions. Two shapes exist in
 * production data:
 *   - CURRENT (this feature onward): options are {preview, clean} objects.
 *   - LEGACY (every order created before this feature shipped): options are
 *     plain strings — the clean fal url, with no derivative ever generated.
 * A legacy row has no watermarked asset to fall back to, so per this
 * feature's spec ("existing orders ... must keep working ... fall back to
 * showing the clean url when no preview exists") its "preview" IS the clean
 * url — that customer's Gate 1 looks exactly as it always has, nothing new
 * regresses. Never throws: a malformed/foreign-shaped row degrades to an
 * empty storyboard rather than 500ing a customer's Gate-1 page or a
 * blocking an in-flight order — callers already treat "no cuts" as
 * "storyboard not ready yet" (see app/approve/[token]/page.tsx Gate1View).
 */
export function normalizeStoryboard(raw: unknown): StoryboardCut[] {
  if (!Array.isArray(raw)) return [];
  return raw.map((cut): StoryboardCut => {
    const c = cut as { scene?: unknown; options?: unknown };
    const scene = typeof c?.scene === "string" ? c.scene : "";
    const rawOptions = c?.options;
    const options: StillOption[] = Array.isArray(rawOptions)
      ? rawOptions
          .map((opt): StillOption | null => {
            if (typeof opt === "string") return { preview: opt, clean: opt }; // legacy row
            const o = opt as { preview?: unknown; clean?: unknown };
            if (o && typeof o.clean === "string") {
              return { preview: typeof o.preview === "string" ? o.preview : o.clean, clean: o.clean };
            }
            return null;
          })
          .filter((o): o is StillOption => o !== null)
      : [];
    return { scene, options };
  });
}

/**
 * Full generation run — awaitable (scripts/tests), while kickStillsGeneration
 * fires it detached for the request path.
 */
export async function runStillsGeneration(order: Order): Promise<void> {
  const falKey = assertEnv("FAL_KEY");
  fal.config({ credentials: falKey });

  if (order.uploadedPhotoUrls.length === 0) {
    throw new Error(`Order ${order.id} has no uploaded photos`);
  }
  const resolved = resolveWorld(order);
  const costume = resolved.costume;
  const arc = resolved.arc.slice(0, NUM_CUTS);

  // LORA-STORYBOARD-SPEC.md §2.7: LoRA training is NOT performed here. It
  // runs in its own upstream Trigger.dev task (trigger/train-lora.ts,
  // runLoraTraining) which persists loraUrl/loraTriggerWord and THEN triggers
  // this task — see this file's header comment for the failure-isolation
  // argument (a ~45-minute training run must never be repeated because of an
  // unrelated stills-side retry). This function only ever READS those two
  // fields off the order it's given. A null loraUrl (training failed,
  // predates this feature, or this order somehow has no photos) is NOT fatal:
  // `lora` stays undefined and every downstream generateGatedTake call falls
  // back to the pre-B1 nano-banana costume chain (see generateTakeOnce) —
  // this order's likeness reverts to the OLD quality bar rather than the
  // order dying.
  const lora: { url: string; triggerWord: string } | undefined =
    order.loraUrl && order.loraTriggerWord
      ? { url: order.loraUrl, triggerWord: order.loraTriggerWord }
      : undefined;
  if (!lora) {
    console.warn(`[stills] order=${order.id}: no LoRA on this order — every take falls back to the pre-B1 nano-banana costume chain`);
  }

  // Stage 0/1 are resumable: if this order already carries an extracted feature
  // description AND an identity portrait (e.g. a re-run, or a seed reusing a
  // known-good pet), reuse them instead of re-spending on the VLM + portrait.
  // A fresh customer order has neither, so it runs the full path.
  let description: string;
  let identityPortraitUrl: string;
  let orderedPhotos = order.uploadedPhotoUrls;

  if (order.petDescription && order.identityPortraitUrl) {
    description = order.petDescription;
    identityPortraitUrl = order.identityPortraitUrl;
    console.log(`[stills] reuse cached description + portrait order=${order.id} (skip stage 0/1)`);
  } else {
    console.log(`[stills] stage 0: analyzing photos order=${order.id}`);
    const a = await analyzePhotos(order.uploadedPhotoUrls);
    description = a.description;
    console.log(`[stills] features: ${description}`);
    console.log(`[stills] best frontal: #${a.bestFrontalIndex}${a.hasFrontal ? "" : " (no clear frontal detected)"}`);

    // Put the clearest front-facing photo FIRST — it seeds the identity portrait
    // (the anchor for every downstream generation).
    orderedPhotos = [
      order.uploadedPhotoUrls[a.bestFrontalIndex],
      ...order.uploadedPhotoUrls.filter((_, i) => i !== a.bestFrontalIndex),
    ].filter(Boolean) as string[];

    console.log(`[stills] stage 1: identity portrait order=${order.id}`);
    // §2.4: gate the portrait itself against the real, best-frontal photo
    // BEFORE it becomes the anchor for the hero sheet and all 18 takes.
    identityPortraitUrl = await generateGatedPortrait(orderedPhotos, description, publicUrl(orderedPhotos[0]), order.id);

    await prisma.order.update({
      where: { id: order.id },
      data: { petDescription: description, identityPortraitUrl, uploadedPhotoUrls: orderedPhotos },
    });
  }

  console.log(`[stills] stage 2: hero sheet order=${order.id} world=${order.tier === "custom" ? "custom" : (order.world ?? "deepspace")}`);
  const heroRefs = [identityPortraitUrl, ...orderedPhotos.slice(0, 2)].map(publicUrl);
  const heroSheet = await generateHeroSheet(heroRefs, description, costume);
  // Persist — the admin's Gate-2 re-shoot needs the same costume anchor later.
  await prisma.order.update({ where: { id: order.id }, data: { heroSheetUrl: heroSheet } });

  // Stage 3: 6 cuts × 3 takes, every take anchored to hero sheet + portrait
  // (no shot-0 chaining — the hero sheet is the single shared anchor). Cuts run
  // sequentially so at most TAKES_PER_CUT (3) renders are in flight at once.
  console.log(`[stills] stage 3: ${NUM_CUTS}×${TAKES_PER_CUT} storyboard order=${order.id} arc=${order.personality}`);
  const realPhotoRef = orderedPhotos[0] ? publicUrl(orderedPhotos[0]) : undefined;
  const heroRef = publicUrl(heroSheet);
  const portraitRef = publicUrl(identityPortraitUrl);
  // §2.2: real photo FIRST — see generateTakeOnce's comment for why order
  // matters (the prompt tells the model the FIRST reference is definitive,
  // so whichever image is first is the one the model actually locks onto).
  // Falls back to the pre-fix ordering (hero sheet first) only if this order
  // somehow has no real photo — see generateGatedTake's comment.
  const hasRealPhotoFirst = !!realPhotoRef;
  const refs = hasRealPhotoFirst
    ? [realPhotoRef, heroRef, portraitRef].filter((u): u is string => !!u)
    : [heroRef, portraitRef].filter((u): u is string => !!u);
  // §4.2: computed once from order.personality — null (custom orders have no
  // personality field) falls into the "add the directive" branch, same as
  // brave/easygoing/timid; only playful is exempt.
  const expression = expressionDirective(order.personality);

  const cleanStoryboard: CleanStoryboardCut[] = [];
  for (let cut = 0; cut < arc.length; cut++) {
    const options = await Promise.all(
      Array.from({ length: TAKES_PER_CUT }, (_, take) =>
        generateGatedTake(
          refs,
          hasRealPhotoFirst,
          description,
          costume,
          arc[cut],
          SHOT_FRAMINGS[cut] ?? SHOT_FRAMINGS[0],
          expression,
          realPhotoRef,
          portraitRef,
          STILL_SEED + cut * 100 + take * 1000,
          `cut ${cut} take ${take}`,
          lora,
          heroRef // §2.2: the hero sheet is B1's ONLY reference image — costume anchor, not identity
        )
      )
    );
    cleanStoryboard.push({ scene: arc[cut], options });
  }

  // Stage 4 (PRICING-PRODUCT-V2-SPEC.md §3.5(C)) — watermark + downscale every
  // clean take into its Gate-1 preview derivative.
  //
  // THROTTLED, and not for rate-limit reasons: an earlier pass fired all 18 at
  // once on the theory that local ffmpeg work needs no throttle, and the first
  // production order to run it crashed the task outright — eighteen concurrent
  // 2K decodes plus their downloads exhausted the machine's memory (Trigger.dev
  // showed "Crashed" with no compute recorded, the same signature the film task
  // hit before it moved to large-1x). The task is on large-1x now too, but a
  // fixed-width queue is the actual fix: peak memory stops scaling with the
  // number of takes, so adding cuts later can't quietly re-break this.
  //
  // watermarkTakeForPreview never throws — one take's derivative failing falls
  // back to that take's clean url (logged) rather than failing the order.
  if (!WATERMARK_PREVIEWS_ENABLED) {
    // Off until the refund it defends exists — see WATERMARK_PREVIEWS_ENABLED.
    // preview === clean is the same shape a failed render produces, so nothing
    // downstream can tell the difference.
    console.log(`[stills] stage 4 skipped (watermark previews disabled) order=${order.id}`);
    await completeStillsGeneration(
      order.id,
      cleanStoryboard.map((cut) => ({
        scene: cut.scene,
        options: cut.options.map((clean) => ({ clean, preview: clean })),
      }))
    );
    return;
  }
  console.log(`[stills] stage 4: watermarking ${cleanStoryboard.length}×${TAKES_PER_CUT} previews order=${order.id}`);
  const jobs = cleanStoryboard.flatMap((cut, cutIdx) =>
    cut.options.map((clean, takeIdx) => ({ cutIdx, takeIdx, clean }))
  );
  const previews = new Map<string, string>();
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.min(WATERMARK_CONCURRENCY, jobs.length) }, async () => {
      for (let i = next++; i < jobs.length; i = next++) {
        const { cutIdx, takeIdx, clean } = jobs[i];
        previews.set(
          `${cutIdx}:${takeIdx}`,
          await watermarkTakeForPreview(clean, `order=${order.id}-cut=${cutIdx}-take=${takeIdx}`)
        );
      }
    })
  );
  const storyboard: StoryboardCut[] = cleanStoryboard.map((cut, cutIdx) => ({
    scene: cut.scene,
    options: cut.options.map((clean, takeIdx) => ({
      clean,
      preview: previews.get(`${cutIdx}:${takeIdx}`) ?? clean,
    })),
  }));

  await completeStillsGeneration(order.id, storyboard);
}

/**
 * Gate-2 re-shoot — regenerate ONE cut's still because its LOOK is off (the
 * admin's reason steers the retake, e.g. "too CGI, make it photoreal"). Same
 * scene/framing/costume as the customer-approved cut, fresh seed, identity
 * gate, style rules enforced. Refs prefer the persisted hero sheet; orders
 * from before it was persisted fall back to another approved cut as the
 * costume anchor. Persists the swap (chosenStills + whitelist) and returns
 * the new still URL for the film pipeline to animate.
 */
export async function reshootCutStill(
  order: Order,
  cutIndex: number,
  reason?: string
): Promise<string> {
  assertEnv("FAL_KEY");
  fal.config({ credentials: process.env.FAL_KEY });

  const portrait = order.identityPortraitUrl;
  if (!portrait) throw new Error(`order ${order.id} has no identityPortraitUrl`);
  const storyboard = (order.storyboardOptions as StoryboardCut[] | null) ?? [];
  const resolved = resolveWorld(order);
  const scene = storyboard[cutIndex]?.scene ?? resolved.arc[cutIndex];
  if (!scene) throw new Error(`order ${order.id} has no scene for cut ${cutIndex}`);
  const description = order.petDescription ?? "the pet shown in the reference images";
  const costume = resolved.costume;

  const costumeAnchorRaw =
    order.heroSheetUrl ?? order.chosenStills.find((_, i) => i !== cutIndex);
  const costumeAnchor = costumeAnchorRaw ? publicUrl(costumeAnchorRaw) : undefined;
  const portraitRef = publicUrl(portrait);
  // §2.1/§2.2: real photo is the gate reference AND goes first in refs, same
  // as every other generateGatedTake caller — see that function's comment.
  const realPhotoRef = order.uploadedPhotoUrls[0] ? publicUrl(order.uploadedPhotoUrls[0]) : undefined;
  const hasRealPhotoFirst = !!realPhotoRef;
  const refs = hasRealPhotoFirst
    ? [realPhotoRef, costumeAnchor, portraitRef].filter((u): u is string => !!u)
    : [costumeAnchor, portraitRef].filter((u): u is string => !!u);
  // §2.1/§2.7: reuse the order's own trained LoRA — this is NOT a training
  // call site (see runLoraTraining's doc comment: the train-pet-lora task is
  // the only place that trains). `undefined` here (no LoRA yet, or training
  // failed for this order) falls back to the pre-B1 chain above, unchanged.
  const lora = order.loraUrl && order.loraTriggerWord ? { url: order.loraUrl, triggerWord: order.loraTriggerWord } : undefined;

  const directed = reason?.trim()
    ? `${scene}. Director's retake note, follow it strictly: ${reason.trim()}`
    : scene;

  console.log(`[stills] re-shoot cut ${cutIndex} order=${order.id}${reason ? ` reason="${reason}"` : ""}`);
  const url = await generateGatedTake(
    refs,
    hasRealPhotoFirst,
    description,
    costume,
    directed,
    SHOT_FRAMINGS[cutIndex] ?? SHOT_FRAMINGS[0],
    expressionDirective(order.personality),
    realPhotoRef,
    portraitRef,
    // Fresh seed family per re-shoot so the retake never repeats the original.
    STILL_SEED + cutIndex * 100 + (Date.now() % 100000),
    `re-shoot cut ${cutIndex}`,
    lora,
    costumeAnchor // §2.2: B1's ONLY reference image — costume anchor, not identity
  );

  const chosenStills = [...order.chosenStills];
  chosenStills[cutIndex] = url;
  await prisma.order.update({
    where: { id: order.id },
    data: { chosenStills, conceptImageUrls: [...order.conceptImageUrls, url] },
  });
  return url;
}

/**
 * Gate-1 CUSTOMER re-roll — B2-SAFETY-NET-SPEC.md §3.1. Regenerates ALL
 * THREE takes of one cut (unlike reshootCutStill above, which is the admin's
 * post-approval single-shot Gate-2 tool and only ever produces one take).
 * No customer instruction: same scene/costume/identity as the original,
 * fresh seeds only (see rerollSeedBase above for why they can never repeat
 * that cut's prior artwork).
 *
 * `rerollCount` MUST be the value app/api/orders/reroll-cut/route.ts's
 * guarded `updateMany` just committed (order-wide, 1..STORYBOARD_REROLL_CAP)
 * — it is the sole source of this call's seed-band uniqueness, so the
 * caller reserving the slot atomically BEFORE calling this function (not
 * after) is what makes two concurrent re-rolls of the same cut land in
 * different, non-colliding bands rather than racing each other's seeds.
 *
 * Persists by re-reading the order immediately before writing (rather than
 * trusting the `order` snapshot the caller passed in, which may be tens of
 * seconds stale by the time generation finishes): a concurrent re-roll of a
 * DIFFERENT cut landing in that window must not be clobbered. This is the
 * same non-atomic read-modify-write shape reshootCutStill above already
 * uses for chosenStills — this function is just slightly more careful about
 * WHEN it reads, because a 3-take re-roll takes long enough for that window
 * to matter more.
 */
export async function rerollCutTakes(
  order: Order,
  cutIndex: number,
  rerollCount: number
): Promise<StoryboardCut> {
  assertEnv("FAL_KEY");
  fal.config({ credentials: process.env.FAL_KEY });

  const portrait = order.identityPortraitUrl;
  if (!portrait) throw new Error(`order ${order.id} has no identityPortraitUrl`);

  const storyboard = normalizeStoryboard(order.storyboardOptions);
  const resolved = resolveWorld(order);
  const scene = storyboard[cutIndex]?.scene ?? resolved.arc[cutIndex];
  if (!scene) throw new Error(`order ${order.id} has no scene for cut ${cutIndex}`);

  const description = order.petDescription ?? "the pet shown in the reference images";
  const costume = resolved.costume;
  const framing = SHOT_FRAMINGS[cutIndex] ?? SHOT_FRAMINGS[0];
  const expression = expressionDirective(order.personality);
  const portraitRef = publicUrl(portrait);
  // Same anchor selection as reshootCutStill/generateGatedTake's other
  // callers — a re-roll must lock the same costume/identity as the original
  // 18 takes, or "re-roll" would silently become "redesign".
  const heroRef = order.heroSheetUrl ? publicUrl(order.heroSheetUrl) : undefined;
  // §2.1/§2.2: real photo is the gate reference AND goes first in refs.
  const realPhotoRef = order.uploadedPhotoUrls[0] ? publicUrl(order.uploadedPhotoUrls[0]) : undefined;
  const hasRealPhotoFirst = !!realPhotoRef;
  const refs = hasRealPhotoFirst
    ? [realPhotoRef, heroRef, portraitRef].filter((u): u is string => !!u)
    : [heroRef, portraitRef].filter((u): u is string => !!u);
  // §2.1/§2.7: reuse the order's own trained LoRA — never retrain on a
  // re-roll. See runLoraTraining's doc comment: the train-pet-lora task is
  // the only call site. `undefined` falls back to the pre-B1 chain above, unchanged.
  const lora = order.loraUrl && order.loraTriggerWord ? { url: order.loraUrl, triggerWord: order.loraTriggerWord } : undefined;

  console.log(`[stills] re-roll cut ${cutIndex} order=${order.id} (order-wide re-roll #${rerollCount})`);
  const seedBase = rerollSeedBase(cutIndex, rerollCount);
  const cleanTakes = await Promise.all(
    Array.from({ length: TAKES_PER_CUT }, (_, take) =>
      generateGatedTake(
        refs,
        hasRealPhotoFirst,
        description,
        costume,
        scene,
        framing,
        expression,
        realPhotoRef,
        portraitRef,
        seedBase + take * 1000,
        `re-roll cut ${cutIndex} reroll#${rerollCount} take ${take}`,
        lora,
        heroRef // §2.2: B1's ONLY reference image — costume anchor, not identity
      )
    )
  );

  // Same {preview, clean} shape stage 4 produces — watermarking is currently
  // OFF (WATERMARK_PREVIEWS_ENABLED above), so preview === clean, exactly the
  // shape a legacy/failed-watermark row already reads as.
  const options: StillOption[] = WATERMARK_PREVIEWS_ENABLED
    ? await Promise.all(
        cleanTakes.map(async (clean, i) => ({
          clean,
          preview: await watermarkTakeForPreview(
            clean,
            `order=${order.id}-cut=${cutIndex}-reroll=${rerollCount}-take=${i}`
          ),
        }))
      )
    : cleanTakes.map((clean) => ({ clean, preview: clean }));

  const newCut: StoryboardCut = { scene, options };

  const latest = await prisma.order.findUniqueOrThrow({ where: { id: order.id } });
  const latestStoryboard = normalizeStoryboard(latest.storyboardOptions);
  latestStoryboard[cutIndex] = newCut;

  await prisma.order.update({
    where: { id: order.id },
    data: {
      storyboardOptions: latestStoryboard,
      // conceptImageUrls is the flat, never-customer-facing audit trail
      // (see completeStillsGeneration's comment) — append, don't replace.
      conceptImageUrls: [...latest.conceptImageUrls, ...cleanTakes],
    },
  });

  return newCut;
}

/**
 * Gate-1 ADMIN re-roll — STORYBOARD-ADMIN-GATE-SPEC.md §3.3. Used from the
 * admin storyboard review screen (app/admin/[orderId]/page.tsx) while an
 * order sits in the pre-approval review queue (status still IMAGE_GENERATING,
 * storyboardOptions populated — see completeStillsGeneration's comment for
 * why that combination IS the queue). Same shape as the customer's
 * rerollCutTakes above — same scene/costume/identity, all three takes of one
 * cut regenerated on fresh seeds, same {preview, clean} persistence — but
 * DELIBERATELY duplicated rather than shared, for two reasons that make
 * sharing the wrong call here:
 *
 * (a) §3.3(a): this must NEVER touch storyboardRerollCount — that column is
 *     the customer's B2 free-reroll budget (3 free, then a refund unlocks),
 *     and an admin re-roll exists specifically to fix OUR quality
 *     miss BEFORE the customer ever sees a bad take. Spending their budget on
 *     our mistake would be exactly backwards. The caller
 *     (app/admin/actions.ts#adminRerollCutAction) atomically increments the
 *     SEPARATE `adminRerollCount` column instead, and passes the
 *     post-increment value in here — this function never writes that column
 *     itself, mirroring how rerollCutTakes never writes
 *     storyboardRerollCount either (its caller, reroll-cut/route.ts, owns
 *     that increment).
 * (b) §3.3(b): the seed must come from adminRerollSeedBase, NOT
 *     rerollSeedBase — see that function's doc comment for the arithmetic
 *     proof that the two can never produce the same seed for the same cut.
 *
 * `adminRerollCount` MUST be the value adminRerollCutAction's guarded
 * `updateMany` just committed (order-wide, 1, 2, 3, …) for the identical
 * "reserve the slot atomically before generating" reason rerollCutTakes'
 * own doc comment gives for storyboardRerollCount.
 */
export async function adminRerollCutTakes(
  order: Order,
  cutIndex: number,
  adminRerollCount: number,
  // Which take to redraw, or undefined for all three. Single-take is the
  // common case in practice: a cut usually has ONE bad option, and replacing
  // the whole trio to fix it throws away takes the reviewer already judged
  // good — and costs three renders to repair one.
  takeIndex?: number
): Promise<StoryboardCut> {
  assertEnv("FAL_KEY");
  fal.config({ credentials: process.env.FAL_KEY });

  const portrait = order.identityPortraitUrl;
  if (!portrait) throw new Error(`order ${order.id} has no identityPortraitUrl`);

  const storyboard = normalizeStoryboard(order.storyboardOptions);
  const resolved = resolveWorld(order);
  const scene = storyboard[cutIndex]?.scene ?? resolved.arc[cutIndex];
  if (!scene) throw new Error(`order ${order.id} has no scene for cut ${cutIndex}`);

  const description = order.petDescription ?? "the pet shown in the reference images";
  const costume = resolved.costume;
  const framing = SHOT_FRAMINGS[cutIndex] ?? SHOT_FRAMINGS[0];
  const expression = expressionDirective(order.personality);
  const portraitRef = publicUrl(portrait);
  // Same anchor selection as rerollCutTakes/reshootCutStill — an admin
  // re-roll must lock the same costume/identity as the original 18 takes, or
  // "re-roll" would silently become "redesign".
  const heroRef = order.heroSheetUrl ? publicUrl(order.heroSheetUrl) : undefined;
  const realPhotoRef = order.uploadedPhotoUrls[0] ? publicUrl(order.uploadedPhotoUrls[0]) : undefined;
  const hasRealPhotoFirst = !!realPhotoRef;
  const refs = hasRealPhotoFirst
    ? [realPhotoRef, heroRef, portraitRef].filter((u): u is string => !!u)
    : [heroRef, portraitRef].filter((u): u is string => !!u);
  // §2.1/§2.7: reuse the order's own trained LoRA — never retrain here either.
  const lora = order.loraUrl && order.loraTriggerWord ? { url: order.loraUrl, triggerWord: order.loraTriggerWord } : undefined;

  // Which take slots this call is responsible for. The seed for a slot is
  // derived from its OWN index either way (seedBase + take*1000), so a
  // single-take re-roll lands in the same seed slot the full re-roll would
  // have used for it — the disjointness argument above is unaffected.
  const targets =
    takeIndex === undefined ? Array.from({ length: TAKES_PER_CUT }, (_, i) => i) : [takeIndex];
  if (targets.some((t) => t < 0 || t >= TAKES_PER_CUT)) {
    throw new Error(`take index out of range for cut ${cutIndex}`);
  }

  console.log(
    `[stills] ADMIN re-roll cut ${cutIndex} ${
      takeIndex === undefined ? "(all takes)" : `take ${takeIndex}`
    } order=${order.id} (order-wide admin re-roll #${adminRerollCount})`
  );
  const seedBase = adminRerollSeedBase(cutIndex, adminRerollCount);
  const cleanTakes = await Promise.all(
    targets.map((take) =>
      generateGatedTake(
        refs,
        hasRealPhotoFirst,
        description,
        costume,
        scene,
        framing,
        expression,
        realPhotoRef,
        portraitRef,
        seedBase + take * 1000,
        `admin re-roll cut ${cutIndex} adminReroll#${adminRerollCount} take ${take}`,
        lora,
        heroRef // §2.2: B1's ONLY reference image — costume anchor, not identity
      )
    )
  );

  // Same {preview, clean} shape as every other producer of a StoryboardCut —
  // watermarking is currently OFF (WATERMARK_PREVIEWS_ENABLED above), so
  // preview === clean.
  const fresh: StillOption[] = WATERMARK_PREVIEWS_ENABLED
    ? await Promise.all(
        cleanTakes.map(async (clean, i) => ({
          clean,
          preview: await watermarkTakeForPreview(
            clean,
            `order=${order.id}-cut=${cutIndex}-adminReroll=${adminRerollCount}-take=${targets[i]}`
          ),
        }))
      )
    : cleanTakes.map((clean) => ({ clean, preview: clean }));

  // Re-read inside the same step that writes: an admin re-rolling two cuts in
  // quick succession must not have the second write clobber the first with a
  // storyboard snapshot taken before it landed.
  const latest = await prisma.order.findUniqueOrThrow({ where: { id: order.id } });
  const latestStoryboard = normalizeStoryboard(latest.storyboardOptions);

  // Splice the fresh takes into their own slots, leaving every other option
  // exactly as the reviewer left it. For a full re-roll `targets` is all three
  // slots, so this is the same result as replacing the cut wholesale.
  const existing = latestStoryboard[cutIndex]?.options ?? [];
  const options: StillOption[] = [...existing];
  targets.forEach((slot, i) => {
    options[slot] = fresh[i];
  });

  const newCut: StoryboardCut = { scene, options };
  latestStoryboard[cutIndex] = newCut;

  await prisma.order.update({
    where: { id: order.id },
    data: {
      storyboardOptions: latestStoryboard,
      conceptImageUrls: [...latest.conceptImageUrls, ...cleanTakes],
    },
  });

  return newCut;
}

/**
 * §2.7 — the front door for the whole storyboard pipeline as of this split:
 * kicks LoRA training FIRST. Callers (submit-photos, approve-treatment, the
 * admin re-kick action) call this instead of kickStillsGeneration directly —
 * kickStillsGeneration itself is unchanged and is what training's own
 * task/branch calls once it's done (or has given up).
 *
 * Mirrors kickStillsGeneration's own three-way dispatch (mock / local dev /
 * Trigger.dev production) below, but with a DIFFERENT failure posture in the
 * local-dev branch: a training failure must never revert the order (§2.7) —
 * it falls back to the pre-B1 chain and stills still runs, exactly like the
 * production path's train-pet-lora task (see trigger/train-lora.ts).
 */
export async function kickLoraTraining(order: Order): Promise<void> {
  if (process.env.VIDEO_PIPELINE_MOCK === "1") {
    // No LoRA in mock mode — kickStillsGeneration's own mock branch fabricates
    // a storyboard from local assets without needing one.
    await kickStillsGeneration(order);
    return;
  }

  // Local dev only (no TRIGGER_SECRET_KEY): detached run, mirroring
  // kickStillsGeneration's own local-dev posture below (fine under a
  // long-lived `next dev`, MUST NOT be the path taken on Vercel — see that
  // function's comment for why).
  if (!process.env.TRIGGER_SECRET_KEY) {
    void (async () => {
      try {
        await runLoraTraining(order); // never throws for an ordinary training failure — see its doc comment
      } catch (e) {
        // Only reached for a genuinely unexpected error (e.g. the persisting
        // prisma.order.update itself throwing) — trainPetLora already
        // swallows an ordinary training failure and returns null instead of
        // throwing. Either way: log, do NOT revert the order, and still
        // continue to stills without a LoRA (§2.7's core requirement).
        console.error(`[lora] local run failed order=${order.id} — continuing to stills without a LoRA`, e);
      } finally {
        // Re-fetch: `order` is a stale snapshot from before training: if
        // training succeeded, runStillsGeneration needs the freshly
        // persisted loraUrl/loraTriggerWord to actually use B1.
        const latest = await prisma.order.findUniqueOrThrow({ where: { id: order.id } });
        await kickStillsGeneration(latest);
      }
    })();
    return;
  }

  await tasks.trigger<typeof trainPetLoraTask>("train-pet-lora", { orderId: order.id });
}

export async function kickStillsGeneration(order: Order): Promise<void> {
  if (process.env.VIDEO_PIPELINE_MOCK === "1") {
    console.log(`[stills:MOCK] kick order=${order.id} — no compute spent`);
    // Fabricate a 6-cut × 3-take storyboard from the local world assets so the
    // Gate-1 wizard, e2e and status machine can run for free. Scenes come from
    // the real arc so the wizard copy matches production.
    const arc = resolveWorld(order).arc.slice(0, NUM_CUTS);
    const assets = ["/assets/world-deepspace.png", "/assets/world-storybook.png", "/assets/world-noir.png"];
    const storyboard: StoryboardCut[] = arc.map((scene, cut) => ({
      scene,
      // Rotate the 3 assets per cut so each cut's takes are visually distinct.
      // preview === clean here on purpose — HARD CONSTRAINT: mock mode must
      // work end to end "without ffmpeg surprises". These are static local LP
      // assets (not real generated art), so there's nothing to protect and no
      // reason to spend an ffmpeg pass on them; this is the exact same shape
      // normalizeStoryboard already produces for a pre-this-feature legacy row.
      options: Array.from({ length: TAKES_PER_CUT }, (_, take) => {
        const url = assets[(cut + take) % assets.length];
        return { preview: url, clean: url };
      }),
    }));
    await prisma.order.update({
      where: { id: order.id },
      data: { identityPortraitUrl: assets[0], petDescription: "mock pet — local assets, no compute" },
    });
    await completeStillsGeneration(order.id, storyboard);
    return;
  }

  // Local dev only (no TRIGGER_SECRET_KEY): detached run, several minutes for
  // the full 18-take chain — fine under a long-lived `next dev`. On Vercel this
  // MUST NOT be the path taken: the function is frozen as soon as the response
  // is sent, which killed generation part-way and left the order stuck in
  // IMAGE_GENERATING with no storyboard and no revert. Production goes through
  // Trigger.dev below, same as the film/poster pipelines.
  if (!process.env.TRIGGER_SECRET_KEY) {
    void runStillsGeneration(order).catch(async (e) => {
      console.error(`[stills] local run failed order=${order.id}, reverting`, e);
      // Custom orders go back to their approved treatment, not the photo form.
      const to =
        order.tier === "custom"
          ? OrderStatus.AWAITING_TREATMENT_APPROVAL
          : OrderStatus.UPLOADING;
      await transitionOrder(
        order.id,
        OrderStatus.IMAGE_GENERATING,
        to,
        "system",
        {},
        "stills generation failed — reverted for retry"
      ).catch((revertErr) =>
        console.error(`[stills] revert also failed order=${order.id}`, revertErr)
      );
    });
    return;
  }

  await tasks.trigger<typeof generateStillsTask>("generate-stills", { orderId: order.id });
}

/**
 * STORYBOARD-ADMIN-GATE-SPEC.md §2/§3.1 — the storyboard is DONE, but the
 * customer does not see it yet. Before this feature, this function saved the
 * storyboard, transitioned IMAGE_GENERATING -> AWAITING_CUSTOMER_APPROVAL, and
 * emailed the CUSTOMER (sendChooseStillEmail). That transition and that email
 * are BOTH GONE from this function now — deliberately, per §0's incident (a
 * take with the dog unreadable inside the costume reached a real customer's
 * Gate 1 because nothing human ever looked at the 18 stills first).
 *
 * What happens now:
 *   1. storyboardOptions is persisted, same as before.
 *   2. The order is left in IMAGE_GENERATING. No transitionOrder call here at
 *      all — `status === IMAGE_GENERATING && storyboardOptions` populated (6
 *      cuts) IS the admin review queue (§2); there is no new OrderStatus
 *      value to move into.
 *   3. The OWNER is emailed instead of the customer (sendAdminStoryboardReviewAlert,
 *      lib/mocks.ts) — someone has to know a review is waiting, or an order
 *      sits here until a human happens to check /admin.
 *   4. Only app/admin/actions.ts#approveStoryboardAction moves the order to
 *      AWAITING_CUSTOMER_APPROVAL and sends sendChooseStillEmail now — that
 *      is the ONLY code path left that can reach Gate 1's customer email; see
 *      that action for the precondition it enforces before doing so (§6
 *      proof 2/5).
 */
export async function completeStillsGeneration(
  orderId: string,
  storyboard: StoryboardCut[]
): Promise<void> {
  // conceptImageUrls keeps the FLAT list of every take's CLEAN url — never
  // customer-facing (not rendered anywhere in app/ or components/, grep-
  // verified), purely an internal audit trail — so it holds the same clean
  // urls it always has, not the watermarked preview derivatives.
  const flat = storyboard.flatMap((cut) => cut.options.map((o) => o.clean));
  const order = await prisma.order.update({
    where: { id: orderId },
    data: { storyboardOptions: storyboard, conceptImageUrls: flat },
  });
  // Non-fatal, deliberately — same posture (and the same real incident) that
  // already justified this pattern for sendChooseStillEmail below §3.1: the
  // storyboard is finished and persisted, so an alert-mail failure must not
  // fail the whole task and retry eighteen fresh renders. Unlike the old
  // customer-mail failure this one is recoverable without a resend button:
  // the order is sitting, correctly, in the admin queue regardless of
  // whether this mail ever lands — an admin who simply checks /admin will
  // still find it. The alert is a nudge to look sooner, not the only way in.
  try {
    await sendAdminStoryboardReviewAlert(order);
  } catch (e) {
    console.error(
      `[stills] order=${orderId} storyboard ready but the ADMIN REVIEW ALERT failed — check ADMIN_ALERT_EMAIL / RESEND_API_KEY / RESEND_FROM_EMAIL. The order is still correctly queued for review (IMAGE_GENERATING + storyboardOptions) and will be found by anyone who checks /admin.`,
      e
    );
  }
  console.log(
    `[stills] order=${orderId} storyboard ready (${storyboard.length} cuts × ${storyboard[0]?.options.length ?? 0} takes) — awaiting ADMIN review (status stays IMAGE_GENERATING)`
  );
}
